# Use official Ubuntu LTS as base
ARG BASE_IMAGE=ubuntu:latest

FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive

# Install required packages
RUN apt-get update                                          &&  \
    apt-get upgrade -y                                      &&  \
    apt-get install -y --no-install-recommends                  \
        binutils                                                \
        git                                                     \
        wget                                                    \
        python3                                                 \
        python3-dev                                             \
        python3-pip                                             \
        python3-setuptools                                      \
        python3-venv                                            \
        libpython3.10                                           \
        locales                                             &&  \
    locale-gen en_US.UTF-8                                  &&  \
    update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8       &&  \
    apt-get clean                                           &&  \
    rm -rf /var/lib/apt/lists/*

# Install Python packages for code generation (jinja2)
RUN pip3 install --no-cache-dir         \
        jinja2                          \
        pyyaml                          \
        pyinstaller
